name: 'Pull Request'
description: 'Pull request template'

body:
  - type: markdown
    attributes:
      value: |
        ## 적용 사항
        - 구성한 자료구조에 대해 작성해주세요.
        
        ## 작업 유형
        - [ ] 코드 수정
        - [ ] 문서 수정
        - [ ] 테스트 추가/수정
        - [ ] 의존성 추가/변경
        - [ ] 설정 파일 수정
        - [ ] 기타

        ## 관련 이슈
        - 이 PR이 관련된 이슈 번호가 있으면 적어주세요. (예: #123)

        ## 확인 사항
        - [ ] 코드 스타일에 맞는지 확인했습니다.
        - [ ] 테스트가 추가/수정되었습니다.
        - [ ] 관련 문서가 업데이트되었습니다.
        - [ ] 의존성 변경에 대한 검토가 완료되었습니다.

        ## 추가 설명
        - 추가적인 설명이나 주의해야 할 점이 있으면 작성해주세요.