name: 'Pull Request'
description: 'Pull request template'

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 적용 내용
        이번 PR에서 적용된 변경 사항을 간단히 정리해주세요.
        - 자료구조 구현/수정/테스트 등 핵심 요약

  - type: textarea
    id: changes
    attributes:
      label: 🔧 변경 사항
      description: 이번 PR에서 구체적으로 어떤 작업을 했나요?
      placeholder: |
        - ArrayListEx 구현
        - 단위 테스트 추가 (add/get/remove 검증)
        - README 사용법 업데이트
    validations:
      required: true

  - type: checkboxes
    id: type
    attributes:
      label: 🏷 작업 유형
      description: 해당되는 작업 유형을 선택하세요.
      options:
        - label: 기능 추가 (Feature)
        - label: 버그 수정 (Bugfix)
        - label: 문서 수정 (Docs)
        - label: 테스트 추가/수정 (Test)
        - label: 의존성 변경 (Dependencies)
        - label: 설정/빌드 수정 (Config)
        - label: 기타 (Other)

  - type: input
    id: issue
    attributes:
      label: 🔗 관련 이슈
      description: '이 PR이 연결된 이슈 번호를 적어주세요. (예: #123)'
      placeholder: '#이슈번호'

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 확인 사항
      description: PR 생성 전에 반드시 확인해주세요.
      options:
        - label: 코드 스타일 및 컨벤션을 준수했습니다.
        - label: 모든 테스트가 통과했습니다.
        - label: 문서(README/위키 등)를 업데이트했습니다.
        - label: 의존성 변경 시 영향도를 검토했습니다.

  - type: textarea
    id: note
    attributes:
      label: 💬 추가 설명
      description: 리뷰어가 알면 좋은 추가적인 설명이나 주의 사항이 있다면 작성해주세요.
      placeholder: |
        - 성능 최적화를 위해 ArrayListEx의 capacity 증가 정책을 1.5배로 설정했습니다.
        - 이후 LinkedList 구현 시 재사용 가능성이 있습니다.
