name: Test
description: 테스트 작성 시 사용
title: "[TEST] 제목을 입력해주세요"
labels: [TEST]
assignees:
  - jho951

body:
  - type: markdown
    attributes:
      value: |
        ### 설명
        ❗️작성하거나 수정해야 할 테스트 케이스에 대해 설명해주세요.

  - type: input
    attributes:
      label: 테스트 유형
      description: '어떤 종류의 테스트를 작업하나요?'
      placeholder: '단위 테스트, 통합 테스트, E2E 테스트 등'
      required: true

  - type: input
    attributes:
      label: '테스트 시나리오'
      description: '테스트할 시나리오는 무엇인가요?'
      placeholder: '테스트가 다룰 시나리오를 설명해주세요.'
      required: true

  - type: input
    attributes:
      label: '예상 결과'
      description: '이 테스트의 예상 결과는 무엇인가요?'
      placeholder: '테스트가 검증할 내용이나 결과를 설명해주세요.'
      required: true

  - type: input
    attributes:
      label: '관련 이슈'
      description: '관련된 이슈 번호가 있나요? (예: #123)'
      placeholder: '예: #123'
      required: false
